## GDS Podcast Text Analysis

### Background

The app explores the transcripts of the Government Digital Service podcast, analyzing the text for sentiment and characteristics

### Useage

This data can be accessed via 3 tabs;
* **Sentiment**, Details two plots showing the sentiment average over the course of one & all episodes. The number of words to analyse average sentiment can be grouped by word bin prompt 
* **Summary**, Details a table of word counts and sentiment averages per episode
* **Characteristics**, Details words that are characteristic of specific episodes, a good analysis to get the gist of what an episode is about

### Acknowledgements

In publishing the transcripts providing an open data source, [The Government Digital Service Podcast](https://open.spotify.com/show/6pIBPKpIWR6Q0kpGDgwgGT)

In developing and licensing for free the **bing** lexicon - [Bing Liu and collaborators](https://www.cs.uic.edu/~liub/FBS/sentiment-analysis.html)

### Developer

**[Github](https://github.com/KurtisAsha)**
**[LinkedIn](https://www.linkedin.com/in/kurtisashasmith/)**
                                              
